sonar.projectKey=pharma-supply-chain
sonar.projectName=Pharma Supply Chain
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.language=js
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/logs/**,**/coverage/**

# Test coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality gate
sonar.qualitygate.wait=true
